category: Kelompok
categories: Kelompok
search: Cari
tag: label
tags: Berbagai Label
tagcloud: Kumpulan Label
tweets: Tweets
prev: Prev
next: Next
comment: Komentar
archive: Arsip
archives: Kumpulan Arsip
archive_a: Arsip
archive_b: "Arsip: %s"
page: Hal %d
recent_posts: Artikel Sebelumnya
about: About