# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: '⏻'
subtitle: 'IndoProfile - Situs Esport Indonesia'
description: 'IndoProfile.com menyajikan kumpulan informasi mengenai permainan Esports (Electronic Sports)'
keywords: 'esports, e-sports indonesia, panduan esport, taruhan esports'
author: 'E-Sport Indonesia'
language: id
timezone: Asia/Jakarta

# URL
## If your site is put in a subdirectory, set url as 'https://yoursite.com/child' and root as '/child/'
url: https://hexo-infinity.netlify.app
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 18
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## https://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 18
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

theme: onepage

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

# Hexo-feed
  feed:
    limit: 0
    order_by: "-date"
    tag_dir: "tag"
    category_dir: "category"
    rss:
        enable: true
        template: "themes/theme/layout/_alternate/rss.ejs"
        output: "rss.xml"
    atom:
        enable: false
        template: 
        output: 
    jsonFeed:
        enable: false
        template: 
        output:

# Hexo Sitemap
    sitemap:
          path: sitemap.xml
          tag: true
          category: true

#hexo-related-posts
related_posts:
      enabled: true
      enable_env_name: prod
      filter_threshold: 0.3
      related_count: 3
      weight:
          title: 0.05
          description: 0.05
          keywords: 0.01
          tags: 0.005
          categories: 0.005
          text: 1
      stemmers:
        - id
      reserved:
        - esport
        - esports

hfc_html:
  enable: yes
  exclude:
hfc_img:
  enable: false
hfc_useref:
  enable: false
hfc_css:
  enable: yes
hfc_js:
  enable: yes
hfc_favicons:
  enable: false

# hexo-generator-amp
# The following settings is the quick start options.

generator_amp:
  templateDir:  amp-template
  assetDistDir: amp-dist
  generateAmpPath: amp/:title 
  logo:
    path:   sample/sample-logo.png
    width:  600
    height: 60
  substituteTitleImage:
    path:   sample/sample-substituteTitleImage.png
    width:  1024
    height: 800
  warningLog: false   # To display warning, please set true.